2022-12-29 17:00:02,775 INFO    StreamThr :30492 [internal.py:wandb_internal():87] W&B internal server running at pid: 30492, started at: 2022-12-29 17:00:02.774268
2022-12-29 17:00:02,776 DEBUG   HandlerThread:30492 [handler.py:handle_request():139] handle_request: status
2022-12-29 17:00:02,778 DEBUG   SenderThread:30492 [sender.py:send_request():317] send_request: status
2022-12-29 17:00:02,786 DEBUG   SenderThread:30492 [sender.py:send():303] send: header
2022-12-29 17:00:02,786 INFO    WriterThread:30492 [datastore.py:open_for_write():75] open: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\run-182q0aff.wandb
2022-12-29 17:00:02,831 DEBUG   SenderThread:30492 [sender.py:send():303] send: run
2022-12-29 17:00:03,249 INFO    SenderThread:30492 [dir_watcher.py:__init__():216] watching files in: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files
2022-12-29 17:00:03,249 INFO    SenderThread:30492 [sender.py:_start_run_threads():928] run started: 182q0aff with start time 1672329602.779266
2022-12-29 17:00:03,250 DEBUG   SenderThread:30492 [sender.py:send():303] send: summary
2022-12-29 17:00:03,250 INFO    SenderThread:30492 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-12-29 17:00:03,255 DEBUG   HandlerThread:30492 [handler.py:handle_request():139] handle_request: check_version
2022-12-29 17:00:03,256 DEBUG   SenderThread:30492 [sender.py:send_request():317] send_request: check_version
2022-12-29 17:00:03,356 DEBUG   HandlerThread:30492 [handler.py:handle_request():139] handle_request: run_start
2022-12-29 17:00:03,369 DEBUG   HandlerThread:30492 [system_info.py:__init__():31] System info init
2022-12-29 17:00:03,369 DEBUG   HandlerThread:30492 [system_info.py:__init__():46] System info init done
2022-12-29 17:00:03,369 INFO    HandlerThread:30492 [system_monitor.py:start():150] Starting system monitor
2022-12-29 17:00:03,370 INFO    SystemMonitor:30492 [system_monitor.py:_start():116] Starting system asset monitoring threads
2022-12-29 17:00:03,370 INFO    HandlerThread:30492 [system_monitor.py:probe():171] Collecting system info
2022-12-29 17:00:03,376 INFO    SystemMonitor:30492 [interfaces.py:start():168] Started cpu
2022-12-29 17:00:03,377 INFO    SystemMonitor:30492 [interfaces.py:start():168] Started disk
2022-12-29 17:00:03,378 INFO    SystemMonitor:30492 [interfaces.py:start():168] Started gpu
2022-12-29 17:00:03,378 INFO    SystemMonitor:30492 [interfaces.py:start():168] Started memory
2022-12-29 17:00:03,391 INFO    SystemMonitor:30492 [interfaces.py:start():168] Started network
2022-12-29 17:00:04,210 DEBUG   HandlerThread:30492 [system_info.py:probe():195] Probing system
2022-12-29 17:00:04,212 DEBUG   HandlerThread:30492 [system_info.py:_probe_git():180] Probing git
2022-12-29 17:00:04,256 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_created():275] file/dir created: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\wandb-summary.json
2022-12-29 17:00:04,286 DEBUG   HandlerThread:30492 [system_info.py:_probe_git():188] Probing git done
2022-12-29 17:00:04,286 DEBUG   HandlerThread:30492 [system_info.py:probe():241] Probing system done
2022-12-29 17:00:04,286 DEBUG   HandlerThread:30492 [system_monitor.py:probe():180] {'os': 'Windows-10-10.0.19044-SP0', 'python': '3.9.7', 'heartbeatAt': '2022-12-29T16:00:04.210797', 'startedAt': '2022-12-29T16:00:02.748266', 'docker': None, 'cuda': None, 'args': ('-wandb', '-data', 'C:/DATA/data/processed/p12_full_seft/', '-epoch', '10', '-per', '20', '-w_pos', '-batch_size', '8', '-lr', '0.00245', '-event_enc', '1', '-state', '-mod', 'none', '-next_mark', '0', '-sample_label', '1', '-user_prefix', '[Op]TEDA__label-'), 'state': 'running', 'program': 'C:\\DATA\\Tasks\\220702\\codes\\thp_final\\Optuna1.py', 'codePath': 'Optuna1.py', 'git': {'remote': 'https://github.com/SimiaoZuo/Transformer-Hawkes-Process.git', 'commit': 'e1fd7ac0a62f2cb674ba64faae889327b931e62c'}, 'email': None, 'root': 'C:/DATA/Tasks/220702/codes/thp_final', 'host': 'LMAMLTP16', 'username': 'hokarami', 'executable': 'C:\\Users\\hokarami\\Anaconda3\\envs\\paper2022\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2304.0, 'min': 0.0, 'max': 2304.0}, 'cpu_freq_per_core': [{'current': 2304.0, 'min': 0.0, 'max': 2304.0}], 'disk': {'total': 950.9365196228027, 'used': 838.2936706542969}, 'gpu': 'Quadro T2000 with Max-Q Design', 'gpu_count': 1, 'gpu_devices': [{'name': 'Quadro T2000 with Max-Q Design', 'memory_total': 4294967296}], 'memory': {'total': 31.750675201416016}}
2022-12-29 17:00:04,286 INFO    HandlerThread:30492 [system_monitor.py:probe():181] Finished collecting system info
2022-12-29 17:00:04,287 INFO    HandlerThread:30492 [system_monitor.py:probe():184] Publishing system info
2022-12-29 17:00:04,287 DEBUG   HandlerThread:30492 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2022-12-29 17:00:04,288 DEBUG   HandlerThread:30492 [system_info.py:_save_pip():67] Saving pip packages done
2022-12-29 17:00:04,288 DEBUG   HandlerThread:30492 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2022-12-29 17:00:04,303 ERROR   HandlerThread:30492 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\hokarami\Anaconda3\envs\paper2022\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\hokarami\Anaconda3\envs\paper2022\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\hokarami\Anaconda3\envs\paper2022\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\hokarami\Anaconda3\envs\paper2022\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2022-12-29 17:00:04,305 DEBUG   HandlerThread:30492 [system_info.py:_save_conda():86] Saving conda packages done
2022-12-29 17:00:04,305 INFO    HandlerThread:30492 [system_monitor.py:probe():186] Finished publishing system info
2022-12-29 17:00:04,307 DEBUG   SenderThread:30492 [sender.py:send():303] send: files
2022-12-29 17:00:04,307 INFO    SenderThread:30492 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-12-29 17:00:04,318 DEBUG   HandlerThread:30492 [handler.py:handle_request():139] handle_request: stop_status
2022-12-29 17:00:04,319 DEBUG   SenderThread:30492 [sender.py:send_request():317] send_request: stop_status
2022-12-29 17:00:04,841 INFO    Thread-79 :30492 [upload_job.py:push():143] Uploaded file C:\Users\hokarami\AppData\Local\Temp\tmp8svmlhp7wandb\1f3nqvlh-wandb-metadata.json
2022-12-29 17:00:05,269 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_created():275] file/dir created: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\wandb-metadata.json
2022-12-29 17:00:05,269 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_created():275] file/dir created: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\conda-environment.yaml
2022-12-29 17:00:05,269 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_created():275] file/dir created: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\requirements.txt
2022-12-29 17:00:05,940 DEBUG   HandlerThread:30492 [handler.py:handle_request():139] handle_request: partial_history
2022-12-29 17:00:06,188 DEBUG   SenderThread:30492 [sender.py:send():303] send: telemetry
2022-12-29 17:00:06,283 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_created():275] file/dir created: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\output.log
2022-12-29 17:00:08,314 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\output.log
2022-12-29 17:00:10,331 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\output.log
2022-12-29 17:00:12,347 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\output.log
2022-12-29 17:00:14,360 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\output.log
2022-12-29 17:00:16,389 INFO    Thread-74 :30492 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\DATA\Tasks\220702\codes\thp_final\wandb\run-20221229_170002-182q0aff\files\output.log
2022-12-29 17:00:19,536 INFO    MainThread:30492 [internal.py:handle_exit():77] Internal process exited
2022-12-29 17:00:19,536 INFO    MainThread:30492 [internal.py:handle_exit():77] Internal process exited
2022-12-29 17:00:19,536 INFO    MainThread:30492 [internal.py:handle_exit():77] Internal process exited
2022-12-29 17:00:19,536 INFO    MainThread:30492 [internal.py:handle_exit():77] Internal process exited
2022-12-29 17:00:19,537 WARNING MsgRouterThr:30492 [router.py:message_loop():74] EOFError seen in message_loop
